// 2-Frontend-Developer/React-apps/todo-app/src/routes/Active.tsx
import styles from "../scss/components/TodoList.module.scss";
import TodoItem from "../components/TodoItem/TodoItem";
import { ITodoItem } from "../interfaces/index";
import { TodoListProps } from './All';

export default function Active({ todos, setTodos }: TodoListProps) {
  const activeTodos = todos.filter((todo: ITodoItem) => !todo.completed);
  return (
      <ul className={styles.container}>
        {activeTodos.map((todo: ITodoItem) => (
          <li key={todo.id}>
            <TodoItem todoItem={todo} todos={todos} setTodos={setTodos} />
          </li>
        ))}
      </ul>
  );
}

// 2-Frontend-Developer/Vue-apps/todo-app/src/views/Active.vue
<template>
  <div class="container">
    <add-todo @add-todo="addTodo" />
    <ul class="todo-list">
      <li v-for="todo in todoActive" :key="todo.id">
        <todo-item
          :todo="todo"
          @update-todo="updateTodo"
          @delete-todo="deleteTodo"
        />
      </li>
    </ul>
  </div>
</template>

<script>
import AddTodo from "@/components/AddTodo.vue";
import TodoItem from "@/components/TodoItem.vue";

export default {
  name: "Active",
  props: ["todoList"],
  components: {
    AddTodo,
    TodoItem,
  },
  computed: {
    todoActive() {
      return this.todoList?.filter((todo) => !todo.completed);
    },
  },
  methods: {
    addTodo(todo) {
      this.$emit("addTodo", todo);
    },
    deleteTodo(todoId) {
      this.$emit("deleteTodo", todoId);
    },
    updateTodo(newTodo) {
      this.$emit("updateTodo", newTodo);
    },
  },
};
</script>
