// 2-Frontend-Developer/Vue-apps/todo-app/src/views/Completed.vue
<template>
  <div class="container">
    <ul class="todo-list">
      <li v-for="todo in todoCompleted" :key="todo.id">
        <todo-item
          :todo="todo"
          @update-todo="updateTodo"
          @delete-todo="deleteTodo"
        />
      </li>
    </ul>
    <delete-all-button
      v-if="todoCompleted.length > 0"
      @delete-completed-todos="deleteCompletedTodos"
    />
  </div>
</template>

<script>
import TodoItem from "@/components/TodoItem.vue";
import DeleteAllButton from "@/components/DeleteAllButton.vue";

export default {
  name: "Completed",
  components: {
    DeleteAllButton,
    TodoItem,
  },
  props: ["todoList"],
  computed: {
    todoCompleted() {
      return this.todoList?.filter((todo) => todo.completed);
    },
  },
  methods: {
    deleteTodo(todoId) {
      this.$emit("deleteTodo", todoId);
    },
    updateTodo(newTodo) {
      this.$emit("updateTodo", newTodo);
    },
    deleteCompletedTodos() {
      this.$emit("deleteCompletedTodos");
    },
  },
};
</script>

// 2-Frontend-Developer/React-apps/todo-app/src/routes/Completed.tsx
import styles from "../scss/components/TodoList.module.scss";
import TodoItem from "../components/TodoItem/TodoItem";
import { ITodoItem } from "../interfaces/index";
import { TodoListProps } from "./All";

export default function Completed({ todos, setTodos }: TodoListProps) {
  const completedTodos = todos.filter((todo: ITodoItem) => todo.completed);
  return (
    <ul className={styles.container}>
      {completedTodos.map((todo: ITodoItem) => (
        <li key={todo.id}>
          <TodoItem todoItem={todo} todos={todos} setTodos={setTodos} />
        </li>
      ))}
    </ul>
  );
}
